### ISSUE TITLE
Valgrind seems to think that nics aren't getting freed upon fi_close of an ep.

### ISSUE THREAD

**Issue by bturrubiates** [ofi-cray/libfabric-cray#145] opened 2015-05-06 23:03 UTC
I'm calling ep_close. Doesn't seem to release nics.

```
==13158== 655,360 bytes in 1 blocks are definitely lost in loss record 7 of 7
==13158==    at 0x4C26FFB: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==13158==    by 0x41CA87: _gnix_nic_tx_freelist_init (gnix_nic.c:67)
==13158==    by 0x41CEB9: gnix_nic_alloc (gnix_nic.c:302)
==13158==    by 0x4181C7: gnix_ep_open (gnix_ep.c:570)
==13158==    by 0x411AB5: fi_endpoint (fi_endpoint.h:155)
==13158==    by 0x4118D1: allocator_setup (allocator.c:71)
==13158==    by 0x412C16: run_test_child (runner.c:134)
==13158==    by 0x413039: run_worker (process.c:67)
==13158==    by 0x413141: spawn_test_worker (process.c:93)
==13158==    by 0x41296D: run_test (runner.c:183)
==13158==    by 0x412EE1: criterion_run_all_tests (runner.c:115)
==13158==    by 0x40331B: main (main.c:186)
```

**Comment by sungeunchoi** [comment] 2015-05-27 16:36
Duplicate of #173

**Closed as completed by sungeunchoi** 2015-05-27 16:36 UTC
