### ISSUE TITLE
GNI provider: fi_atomicvalid APIs should return FI_EOPNOTSUPP for an invalid AMO operator and data type combination

### ISSUE THREAD

**Issue by tonyzinger** [ofi-cray/libfabric-cray#1136] opened 2017-01-06 19:34 UTC
Currently the GNI provider, for the fi_atomicvalid(), fi_fetch_atomicvalid() and fi_compare_atomicvalid() APIs returns the error, FI_ENOENT, for an invalid AMO operator and data type combination.

From my test case using the gni provider for the AMO CSWAP operator with a int16 data type, I get the erorr FI_ENOENT.  The following output shows this:
fi_compare_atomicvalid: Not Supported op: CSWAP, data type: INT16 returned 2 (No such file or directory)

From the fi_atomic man page, it states that the return value should be:
-FI_EOPNOTSUPP : The requested atomic operation is not supported on this endpoint.

-FI_ENOENT is not listed as one of the return values.

**Comment by sungeunchoi** [comment] 2017-01-06 21:13
Duplicate of #1048

**Closed as completed by sungeunchoi** 2017-01-06 21:13 UTC
