### ISSUE TITLE
libfabric completion queue event ordering

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#288] opened 2015-07-28 21:02 UTC
The underlying aries HW doesn't order generation of hw CQEs.  Thus the most efficient way handling of libfabric completion queue ordering is basically not to have any, i.e. `FI_ORDER_NONE` for both tx and rx.  However its possible an app requires `FI_ORDER_STRICT`.  

The gni provider should probably at least have infrastructure for supporting the `FI_ORDER_STRICT`, although at present there does not appear to be an application which requires this capability either for tx or rx contexts.

**Comment by sungeunchoi** [comment] 2015-09-10 21:49
Duplicate of #146

**Closed as completed by sungeunchoi** 2015-09-10 21:49 UTC
