### ISSUE TITLE
Crash in GASNet testalign running large number of asynchronous RMA read requests.

### ISSUE THREAD

**Issue by epaulson10** [ofi-cray/libfabric-cray#1199] opened 2017-02-10 23:40 UTC
Hi there,

I am testing out GASNet using the gni provider and I am running into this issue. I am running GASNet's testalign, which has some sections that issue a large number of read/write RMA ops at once (default: 1000) at different alignments. I am seeing a crash on the part of the test that executes a large number of rma read requests. The call stack is below:

[0] #6  <signal handler called>
[0] #7  0x00002aaaab733875 in raise () from /lib64/libc.so.6
[0] #8  0x00002aaaab734e51 in abort () from /lib64/libc.so.6
[0] #9  0x00002aaaaad53a09 in _gnix_rma_post_rdma_chain_req () from /global/homes/e/epaulson/lib/libfabric.so.1
[0] #10 0x00002aaaaad67abe in _gnix_vc_queue_tx_req () from /global/homes/e/epaulson/lib/libfabric.so.1
[0] #11 0x00002aaaaad57e61 in _gnix_rma () from /global/homes/e/epaulson/lib/libfabric.so.1
[0] #12 0x00002aaaaad1bc49 in gnix_ep_read () from /global/homes/e/epaulson/lib/libfabric.so.1
[0] #13 0x000000000045112b in fi_read (ep=0x8ae8b0, buf=0x94b000, len=32768, desc=0x0, src_addr=3, addr=46915105341441, key=56498863703206, context=0x940b78) at /global/homes/e/epaulson/include/rdma/fi_rma.h:101
[0] #14 0x0000000000459334 in gasnetc_rdma_get (dest_addr=0x94b000, dest=1, src_addr=0x2aab46304001, nbytes=32768, ctxt_ptr=0x940b78) at /global/u2/e/epaulson/gasnet/ofi-conduit/gasnet_ofi.c:1237
[0] #15 0x000000000043aa76 in gasnete_get_nbi_bulk (dest=0x94b000, node=1, src=0x2aab46304001, nbytes=32768) at /global/u2/e/epaulson/gasnet/ofi-conduit/gasnet_extended.c:510
[0] #16 0x000000000040b127 in _gasnet_get_nbi_bulk (dest=0x94b000, node=1, src=0x2aab46304001, nbytes=32768) at /global/u2/e/epaulson/gasnet/extended-ref/gasnet_extended.h:355
[0] #17 0x0000000000412d34 in oneway_nbi_test (iters=1000, nbytes=32768, alignment=1) at /global/u2/e/epaulson/gasnet/tests/testalign.c:184
[0] #18 0x0000000000413d49 in main (argc=1, argv=0x7fffffff6938) at /global/u2/e/epaulson/gasnet/tests/testalign.c:361

Poking around in the GNI code, I see that this from an assert being thrown in this chunk of code:
 if (req->int_tx_buf_e == NULL) {
     req->int_tx_buf_e = _gnix_ep_get_int_tx_buf(ep);
     if (req->int_tx_buf_e == NULL) {
         GNIX_FATAL(FI_LOG_EP_DATA, "RAN OUT OF INT_TX_BUFS");
         return -FI_ENOSPC;
         /* TODO Create growable list of buffers */
     }
 }

To me it seems like instead of an assertion, this should bubble back up to the caller in the form of -FI_EAGAIN so they know to poll to free up some of these buffers. Although it does appear that this code path is being actively worked on based off of the TODO.

This is only occurring on the head of the repository, not on the 1.4 release.

**Comment by hppritcha** [comment] 2017-02-13 16:32
This needs to be fixed for 1.5.  I'm assigning this to @a-abraham since git blame shows he worked in this area of the code most recently.

**Comment by hppritcha** [comment] 2017-02-23 03:20
@sungeunchoi  should this be reassigned to someone working on the GNI provider?

**Comment by hppritcha** [comment] 2017-02-28 19:13
@epaulson10 do you have a reproducer for this?  A set of instructions to reproduce this problem would be great.

**Comment by hppritcha** [comment] 2017-02-28 19:14
Actually it looks like all we need is instructions on how to configure gasnet for libfabric so we can reproduce.

**Comment by epaulson10** [comment] 2017-03-01 23:03
So grab the latest version of the develop branch from GASNet's upstream here: https://bitbucket.org/berkeleylab/gasnet 

Configure GASNet: 
$ ./Bootstrap
$ ./configure --enable-ofi --with-ofihome=<your install dir> --with-ofi-provider=gni --with-pmi=<your pmi dir>

Compile and run the test:
$ cd ofi-conduit
$ make seq testalign
$ salloc -N 2
$ srun -n 2 ./testalign

**Closed as completed** 2017-04-25 01:31 UTC
Labels: bug
